### PR TITLE
colors can now be specified with only hex strings

### PR DESCRIPTION
**Pull request by kaivogelgesang**
this allows color definitions like:
```json
"primary": "0xb3ff00"
```

### CODE REVIEW

**Comment by tjbcg** [comment]
Update: works with 
```json
"back_transparent":  0,
```
But now the error has moved

**Comment by tjbcg** [comment]
Re-update: see #8

**Comment by tjbcg** [comment]
Update again, now that i've got powerline to work, I figured out `0` (cterm) is not transparent. So this indeed breaks transparency.

**Comment by tjbcg** [comment]
Can be fixed by replacing this:
```python
if type(color) == int:
```

by this:
```python
if type(color) == int or type(color) == bool:
```

**Comment by PH111P** [comment]
This bug should be fixed, too.

**Pull request merged**
